name: assessment
version: '0.1.0.0'
category: Data
author: Alex Milkov
maintainer: amilkov3@gmail.com
copyright: 2018 Alex Milkov
license: BSD3
library:
  source-dirs: src
  exposed-modules:
  - Problem1
  - Problem2
  - Problem4
  dependencies:
  - base >=4.7 && <5
  - text
  - split
  - unordered-containers
  - vector
tests:
  confide-test:
    main: Test.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - assessment
    - tasty
    - tasty-hunit
    - text

